### ISSUE TITLE
Add Title/Prefix, Suffix options to Personal

### ISSUE THREAD

**Issue by memilanuk** [lk-geimfari/church#34]
As an example, have something like `person.title()` that would randomly pull from values such as 'Dr.', 'Sir', 'Honorable' (or ' '), or `person.prefix(gender=)` that returns 'Mr.', 'Mrs.', 'Ms.' as appropriate.

Also, similar for suffix to the surname... either `person.surname(suffix=True)` or `person.suffix()` to return values such as 'Sr', 'Jr', 'III', 'PhD', etc.

**Comment by lk-geimfari** [comment]
If you want to get degree, then use personal.qualification() that return 'Bachelor', 'Master' or 'PhD' (for `en`).

The problem is that the prefixes of the names is not available in all languages. For example in Russian we have not name prefix.

We will try to add this capability. Thank you for idea!

**Comment by lk-geimfari** [comment]
We also can add prefix for `person.profession()`

Example: 
```python
from church import Personal

person = Personal('en')

person.job(prefix=True)

# Output: Sr. Technical Support Engineer
```

**Comment by lk-geimfari** [comment]
@memilanuk It's done!

```python
from church import Personal

p = Person('en')

# available types: typical, aristocratic, religious, academic
title = p.title(type_='academic')

```
